#ifndef COSTSNB_CLISRV_ENCODER_H
#define COSTSNB_CLISRV_ENCODER_H


// This file was autogenerated
#include "costsnb_clisrv_structs.h"

extern void Encode_message(char *buf, Handshake_srv *msg);
extern void Encode_message(char *buf, Handshake_cli_ack *msg);
extern void Encode_message(char *buf, Str_data *msg);

#endif

