#include <netdb.h>
#include <stdint.h>
#include <arpa/inet.h>


// This file was autogenerated
#include "costsnb_clisrv_structs.h"
#include "costsnb_clisrv_opcodes.h"

void Encode_message(char *buf, Handshake_srv *msg) {
  std::memcpy(buf, msg, sizeof(Handshake_srv));
  Handshake_srv *msg2 = (Handshake_srv*)buf;
  msg2->opcode = htons(1);
  msg2->vsn = htons(msg2->vsn);
}

void Encode_message(char *buf, Handshake_cli_ack *msg) {
  std::memcpy(buf, msg, sizeof(Handshake_cli_ack));
  Handshake_cli_ack *msg2 = (Handshake_cli_ack*)buf;
  msg2->opcode = htons(2);
}

void Encode_message(char *buf, Str_data *msg) {
  std::memcpy(buf, msg, sizeof(Str_data));
  Str_data *msg2 = (Str_data*)buf;
  msg2->opcode = htons(3);
  msg2->seq_num = htonl(msg2->seq_num);
  msg2->data_size = htonl(msg2->data_size);
  msg2->last = (msg2->last);
}


