#include <netdb.h>
#include <stdint.h>
#include <arpa/inet.h>


// This file was autogenerated
#include "costsnb_clisrv_structs.h"
#include "costsnb_clisrv_opcodes.h"

App_message *Parse_message(char *buf) {
  uint16_t opcode = *((uint16_t*)(buf));
  opcode = ntohs(opcode);
  switch (opcode) {
  case 1: {
    Handshake_srv *msg = new Handshake_srv();
    std::memcpy(msg, buf, sizeof(Handshake_srv));
    msg->opcode = opcode;
    msg->vsn = ntohs(msg->vsn);
    return msg;
  }
  case 2: {
    Handshake_cli_ack *msg = new Handshake_cli_ack();
    std::memcpy(msg, buf, sizeof(Handshake_cli_ack));
    msg->opcode = opcode;
    return msg;
  }
  case 3: {
    Str_data *msg = new Str_data();
    std::memcpy(msg, buf, sizeof(Str_data));
    msg->opcode = opcode;
    msg->seq_num = ntohl(msg->seq_num);
    msg->data_size = ntohl(msg->data_size);
    msg->last = (msg->last);
    return msg;
  }
  default:
    return nullptr;
  };
  return nullptr;
}
