<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text" indent="yes"/>

<xsl:template match="/">
  <xsl:text>#ifndef COSTSNB_CLISRV_STRUCTS_H&#10;</xsl:text>
  <xsl:text>#define COSTSNB_CLISRV_STRUCTS_H&#10;&#10;</xsl:text>
  <xsl:text>&#10;// This file was autogenerated&#10;</xsl:text>
  <xsl:text>#include &#60;stdint.h&#62;&#10;</xsl:text>
  <xsl:text>#include &#60;cstring&#62;&#10;</xsl:text>
  <xsl:text>&#10;</xsl:text>
  <xsl:text>#pragma pack(push,1)&#10;</xsl:text>
  <xsl:text>struct App_message {&#10;</xsl:text>
  <xsl:text>  uint16_t opcode;&#10;</xsl:text>
  <xsl:text>};&#10;&#10;</xsl:text>
  <xsl:apply-templates select="messages"/>
  <xsl:text>#pragma pack(pop)&#10;</xsl:text>
  <xsl:text>#endif&#10;&#10;</xsl:text>
</xsl:template>

<xsl:template match="messages">
  <xsl:apply-templates select="message"/>
</xsl:template>

<xsl:template match="message"> 
  <xsl:text>struct </xsl:text>
  <xsl:value-of select="name"/>
  <xsl:text> : App_message{</xsl:text>
  <xsl:text>&#10;</xsl:text>
  <xsl:apply-templates select="fields"/>
  <xsl:text>};&#10;&#10;</xsl:text>
</xsl:template>

<xsl:template match="fields">
  <xsl:apply-templates select="field"/>
</xsl:template>

<xsl:template match="field">
  <xsl:text>  </xsl:text>
  <xsl:choose>
    <xsl:when test="size='8'">
      <xsl:text>uint8_t </xsl:text>
    </xsl:when>
    <xsl:when test="size='16'">
      <xsl:text>uint16_t </xsl:text>
    </xsl:when>
    <xsl:when test="size='32'">
      <xsl:text>uint32_t </xsl:text>
    </xsl:when>
  </xsl:choose>
  <xsl:value-of select="name"/>
  <xsl:if test="array!=''">
    <xsl:text>[</xsl:text><xsl:value-of select="array"/><xsl:text>]</xsl:text>
  </xsl:if>
  <xsl:text>;&#10;</xsl:text>
</xsl:template>

</xsl:stylesheet>
