<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text" indent="yes"/>

<xsl:template match="/">
  <xsl:text>#ifndef COSTSNB_CLISRV_OPCODES_H&#10;</xsl:text>
  <xsl:text>#define COSTSNB_CLISRV_OPCODES_H&#10;&#10;</xsl:text>
  <xsl:text>&#10;// This file was autogenerated&#10;</xsl:text>
  <xsl:apply-templates select="messages"/>
  <xsl:text>&#10;#endif&#10;</xsl:text>
</xsl:template>

<xsl:template match="messages">
  <xsl:apply-templates select="message"/>
</xsl:template>

<xsl:template match="message"> 
  <xsl:text>#define OPCODE_</xsl:text>
  <!-- <xsl:value-of select="name"/> -->
  <xsl:value-of select="translate(name, 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')"/>
  <xsl:text> </xsl:text>
  <xsl:value-of select="opcode"/>
  <xsl:text>&#10;</xsl:text>
</xsl:template>

</xsl:stylesheet>
