<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text" indent="yes"/>

<xsl:template match="/">
  <xsl:text>#include &#60;netdb.h&#62;&#10;</xsl:text>
  <xsl:text>#include &#60;stdint.h&#62;&#10;</xsl:text>
  <xsl:text>#include &#60;arpa/inet.h&#62;&#10;</xsl:text>
  <xsl:text>&#10;</xsl:text>
  <xsl:text>&#10;// This file was autogenerated&#10;</xsl:text>
  <xsl:text>#include "costsnb_clisrv_structs.h"&#10;</xsl:text>
  <xsl:text>#include "costsnb_clisrv_opcodes.h"&#10;</xsl:text>
  <xsl:text>&#10;</xsl:text>
  <xsl:apply-templates select="messages"/>
  <xsl:text>&#10;</xsl:text>
</xsl:template>

<xsl:template match="messages">
  <xsl:apply-templates select="message"/>
</xsl:template>

<xsl:template match="message"> 
  <xsl:text>void Encode_message(char *buf, </xsl:text><xsl:value-of select="name"/><xsl:text> *msg) {&#10;</xsl:text>
  <xsl:text>  std::memcpy(buf, msg, sizeof(</xsl:text><xsl:value-of select="name"/><xsl:text>));&#10;</xsl:text>
  <xsl:text>  </xsl:text><xsl:value-of select="name"/><xsl:text> *msg2 = (</xsl:text><xsl:value-of select="name"/><xsl:text>*)buf;&#10;</xsl:text>
  <xsl:text>  msg2->opcode = htons(</xsl:text><xsl:value-of select="opcode"/><xsl:text>);&#10;</xsl:text>
  <xsl:apply-templates select="fields"/>
  <xsl:text>}&#10;&#10;</xsl:text>
</xsl:template>

<xsl:template match="fields">
  <xsl:apply-templates select="field"/>
</xsl:template>

<xsl:template match="field">
  <xsl:if test="not (array)">
    <xsl:text>  msg2-></xsl:text><xsl:value-of select="name"/><xsl:text> = </xsl:text>
    <xsl:choose> 
      <xsl:when test="size='16'">
        <xsl:text>htons</xsl:text>
      </xsl:when>
      <xsl:when test="size='32'">
        <xsl:text>htonl</xsl:text>
      </xsl:when>
    </xsl:choose>
    <xsl:text>(msg2-></xsl:text><xsl:value-of select="name"/><xsl:text>);&#10;</xsl:text>
  </xsl:if>
</xsl:template>

</xsl:stylesheet>
