<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text" indent="yes"/>

<xsl:template match="/">
  <xsl:text>#ifndef COSTSNB_CLISRV_ENCODER_H&#10;</xsl:text>
  <xsl:text>#define COSTSNB_CLISRV_ENCODER_H&#10;&#10;</xsl:text>
  <xsl:text>&#10;// This file was autogenerated&#10;</xsl:text>
  <xsl:text>#include "costsnb_clisrv_structs.h"&#10;</xsl:text>
  <xsl:text>&#10;</xsl:text>
  <xsl:apply-templates select="messages"/>
  <xsl:text>&#10;</xsl:text>
  <xsl:text>#endif&#10;&#10;</xsl:text>
</xsl:template>

<xsl:template match="messages">
  <xsl:apply-templates select="message"/>
</xsl:template>

<xsl:template match="message"> 
  <xsl:text>extern void Encode_message(char *buf, </xsl:text><xsl:value-of select="name"/><xsl:text> *msg);&#10;</xsl:text>
</xsl:template>

</xsl:stylesheet>
